package ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFBFC2FF)
val md_theme_dark_onPrimary = Color(0xFF202578)
val md_theme_dark_primaryContainer = Color(0xFF383E8F)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFFBEC2FF)
val md_theme_dark_onSecondary = Color(0xFF1F2578)
val md_theme_dark_secondaryContainer = Color(0xFF373E90)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_tertiary = Color(0xFFFFB86F)
val md_theme_dark_onTertiary = Color(0xFF4A2800)
val md_theme_dark_tertiaryContainer = Color(0xFF693C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF918F9A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF5056A9)
val md_theme_dark_surfaceTint = Color(0xFFBFC2FF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)